### PR TITLE
Fix and refactor joystick

### PR DESCRIPTION
**Pull request by troygibb**
My team has been using this panel quite a bit! Thanks for the contribution.

We were running into some issues publishing from it however, which ended up being because it doesn't allow publishing from `geometry_msgs/msg/TwistStamped`. I ended up fixing that issue, and ended up just refactoring the whole thing to be a bit cleaner and more idiomatic React. 

I did a bunch of local, manual testing, so hopefully that will suffice for your means here. Happy to take on any other bugs should they arise.

### CODE REVIEW

**Comment by yulong88888** [comment]
Sorry, I just came back from vacation, so I noticed this PR. I will also test it in the next few days. After passing the test, I will put it on foxglove. Thank you again for your PR.  : )

**Comment by yulong88888** [comment]
Hello, I tested the code you submitted today. There is currently a problem. It seems that the topic and message schema cannot be selected. It may also be a problem with my packaging because I am not very familiar with ts. Can you help me solve the problem? , I also tried to solve this problem myself. Thank you so much.
image

**Comment by yulong88888** [comment]
I found the problem. I am using the melodic version of ros, and the message does not have "msg". I am not sure whether it is a problem caused by ros1 or ros2.
image

**Comment by troygibb** [comment]
Good catch! Updated with the ROS 1 schemas. See latest.

**Comment by yulong88888** [comment]
Thanks for submitting. I just tested it and the previous problem has been solved. However, there is a new problem. When the virtual joystick is dragged for a certain distance and then kept still, the twist message will not be posted again. My previous The code is triggered by a timer, do you have a better solution?

I also learned a lot from your program, thank you again. This is my first open source project with a PR, and I hope we can make it better together.     : )

**Comment by troygibb** [comment]
of course! very happy to help improve this package. 

How are you currently testing this? Would love to be able to repro on my side

**Comment by yulong88888** [comment]
I tested turtlesim_node. This is my shell script. Docker is used here.
```shell
sudo docker run -d -p 6080:80 -p 9090:9090 --name=ros_base -e RESOLUTION=1280x800 --shm-size=512m tiryoh/ros-desktop-vnc:melodic

sudo docker exec -it ros_base bash

sudo apt update
sudo apt upgrade
sudo apt-get install ros-melodic-rosbridge-server

roscore
rosrun turtlesim turtlesim_node
roslaunch rosbridge_server rosbridge_websocket.launch
```

**Comment by troygibb** [comment]
Great thank you!!

Ah ok so I definitely misunderstood the originally functionality slightly, so basically if you don't move your virtual joystick at full throttle we still want to continue publishing. I don't know why I didn't see that before. 

Fixed :) Please take another look when you get a chance!

**Comment by yulong88888** [comment]
Great job, I will submit it to foxglove in the next few days

**Pull request merged**
